
networks:
  skeletonbr:
    driver: bridge

services:
###> doctrine/doctrine-bundle ###
  php:
    container_name: 'php-skeleton'
    networks:
      - skeletonbr
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www/html'
    extra_hosts:
      # for step debugging with Xdebug
      - 'host.docker.internal:host-gateway'
  nginx:
      container_name: 'nginx-skeleton'
      build:
        context: ./docker/nginx
      networks:
        - skeletonbr
      depends_on:
        - php
      ports:
        - 8080:80
      volumes:
        - '.:/var/www/html'
        - './docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf'

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
